### ISSUE TITLE
Cannot access configuration page

### ISSUE THREAD

**Issue by stephenyeargin** [raventools/redmine_zendesk_issue_bridge#3]
Via: https://twitter.com/bertieuk/status/621317743162327040

> [I] am trying to install your `redmine_zendesk_issue_bridge` plugin but get error "The page you were trying to access doesn't exist or has been removed." on issue pages, Plugin config page, etc.

**Comment by stephenyeargin** [comment]
@bertieuk - Can you confirm which version of Redmine you might be running? I only tested it with the 2.6 branch (which is what @raventools runs), but it _shouldn't_ have trouble with other versions.

Also, is it accessing `<your hostname>/settings/plugin/redmine_zendesk_issue_bridge` for the configuration path? You should get a page that looks like:

![](http://s.yearg.in/1K7QlRh)

**Comment by bertieuk** [comment]
Redmine 2.6.5

Yes I get the error when accessing that url. I also get it on the view issue page (my.hostname/issue/1234)

production.log just shows Redmine returning a 404

**Comment by stephenyeargin** [comment]
@bertieuk Interesting. So, I just merged PR #2 that we are using in production. I don't _think_ it will fix the issue you're seeing, but it will certainly help to have it comparing the two. Our production redmine is `2.6.1`, but I doubt that should make a big difference.

**Comment by bertieuk** [comment]
That has worked!

**Comment by bertieuk** [comment]
Get the configuration page and issue pages correctly. Need to get Zendesk agent login details from a colleague tomorrow to completely make sure, but looks to be working! Thanks!

**Comment by punkrokk** [comment]
I'm seeing the same problem - how can I help troubleshoot? I'm on redmine 2.6.6

**Comment by stephenyeargin** [comment]
You may need to restart Redmine to get the routes to update.

**Comment by punkrokk** [comment]
I was able to get it working by checking out the git branch. Thanks for the quick reply.

Cheers,

JP

**Comment by stephenyeargin** [comment]
Cool. :+1:
