### ISSUE TITLE
Cannot find zendesk_api

### ISSUE THREAD

**Issue by mborsalino** [raventools/redmine_zendesk_issue_bridge#5]
I followed the plugin installation and I now see one more field in the redmine tickets "Related zendesk tickets", but only a spinning gif shows up there.  I digged more and found the following in the redmine log file. 

Completed 200 OK in 503ms (Views: 330.8ms | ActiveRecord: 33.5ms)
Started GET "/redmine/issues/2/redmine_zendesk_issue_bridge" for 192.168.7.161 at 2016-10-19 19:02:58 -0700
Processing by RedmineZendeskIssueBridgeController#index as _/_
  Parameters: {"id"=>"2"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 15ms (ActiveRecord: 4.5ms)

LoadError (cannot load such file -- zendesk_api):
  plugins/redmine_zendesk_issue_bridge/app/controllers/redmine_zendesk_issue_bridge_controller.rb:44:in `zendesk_client'
  plugins/redmine_zendesk_issue_bridge/app/controllers/redmine_zendesk_issue_bridge_controller.rb:16:in`related_zendesk_tickets'
  plugins/redmine_zendesk_issue_bridge/app/controllers/redmine_zendesk_issue_bridge_controller.rb:10:in `index'
  lib/redmine/sudo_mode.rb:63:in`sudo_mode'

Now, I did run bundle install from within the plugin folder, and I can successfully run "require 'zendesk_api'" from within the irb shell, so I'm puzzled.  Any help would be appreciated.

**Comment by stephenyeargin** [comment]
You may need to run this to get the proper `bundle install` process kicked off. Running it in the root will only get the resources needed for the app itself, not any installed plugins.

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

Reference: http://www.redmine.org/projects/redmine/wiki/Plugins

**Comment by mborsalino** [comment]
Thanks for your quick reply.  I had already run the command that you suggested, but that was not sufficient.  I ended up going back to the RAILS_ROOT directory and run "bundle install".  That gives an error, suggesting to run "bundle isntall --no-deployment".  

The latter fixed it. It picked up zendesk_api and upon restarting the server everything worked. 

I don't really understand what's going on behind the curtains as I'm entirely new to ruby and redmine. But I thought to post my experiments in case this can help writing more complete instructions. 

Thanks!

**Comment by stephenyeargin** [comment]
:+1:
